# Set update schedule for GitHub Actions

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build"
      include: "scope"
    assignees:
      - "hpidcock"
      - "anvial"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    allow:
      - dependency-name: "golang.org/x/*"
    assignees:
      - "hpidcock"
      - "anvial"
    target-branch: "2.9" # these should always go to 2.9 as it may contain security fixes
