name: "Client Tests"
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - '**.go'
      - 'go.mod'
      - '.github/workflows/client-tests.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:

  test-client-ubuntu:
    name: "Client Tests"
    runs-on: ${{ matrix.os }}
    if: github.event.pull_request.draft == false
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
        cache: true

    - name: "Install Mongo Dependencies: ubuntu-latest"
      if: (matrix.os == 'ubuntu-latest')
      run: |
        make install-mongo-dependencies

    - name: "Install musl"
      shell: bash
      run: |
        sudo make musl-install

    - name: "Test client"
      shell: bash
      run: |
        # Jenkins can perform the full jujud testing.
        TEST_PACKAGES=./cmd/juju/... COVERAGE_CHECK=1 TEST_TIMEOUT="15m" make run-go-tests
        TEST_PACKAGES=./cmd/plugins/... COVERAGE_CHECK=1 TEST_TIMEOUT="15m" make run-go-tests
