name: "Migrate"
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - '**.go'
      - 'go.mod'
      - 'snap/**'
      - '.github/workflows/migrate.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  migrate:
    name: 2.9 -> 3.X
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    strategy:
      fail-fast: false
      matrix:
        # TODO: add microk8s tests
        cloud: ["lxd"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup LXD
        if: matrix.cloud == 'lxd'
        uses: canonical/setup-lxd@90d76101915da56a42a562ba766b1a77019242fd

      - name: Install Juju 2.9
        run: |
          sudo snap set system experimental.parallel-instances=true
          sudo snap install juju --classic --channel 2.9/stable

      - name: Bootstrap a 2.9 controller and model
        run: |
          juju bootstrap lxd test29
          juju add-model test-migrate
          juju deploy ubuntu
          
          # TODO: use juju-restore
          # TODO: add users/permissions/models and test that those migrate over

      - name: Set up Go
        uses: actions/setup-go@v3

      - name: Set up Go env
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Upgrade client to 3.1
        run: |
          sudo snap remove juju --purge
          make go-install &>/dev/null

      - name: Bootstrap 3.1 controller
        run: |
          juju bootstrap lxd test31
          juju switch controller
          juju wait-for application controller

        # TODO: create backup and juju restore

      - name: Set up Snap env
        run: |
          echo "GOPATH=/snap" >> $GITHUB_ENV
          echo "snap/bin" >> $GITHUB_PATH

      - name: Migrate default model to 3.1 controller
        run: |
          juju switch test29
          
          # Ensure application is fully deployed
          juju wait-for application ubuntu
          
          # Wait a few secs for the machine status to update
          # so that migration prechecks pass.
          sleep 10
          
          juju_29 migrate test-migrate test31

      - name: Set up Go env
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Check the migration was successful
        run: |
          set -x
          juju switch test31
          
          # Wait for 'test-migrate' model to come through
          attempt=0
          while true; do
            RES=$(juju models | grep 'test-migrate' || true)
            if [[ -n $RES ]]; then
              break
            fi
            sleep 5
            attempt=$((attempt+1))
            if [ "$attempt" -eq 10 ]; then
              echo "Migration timed out"
              exit 1
            fi
          done
          
          juju switch test-migrate
          juju wait-for application ubuntu
