name: "Smoke"
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - '**.go'
      - 'go.mod'
      - 'testcharms/**'
      - 'tests/main.sh'
      - 'tests/includes/**'
      - 'tests/suites/smoke/**'
      - '.github/workflows/smoke.yml'
      - '.github/setup-lxd/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:

  smoke:
    name: Smoke
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:

    - name: Install Dependencies
      shell: bash
      run: |
        set -euxo pipefail
        echo "/snap/bin" >> $GITHUB_PATH
        sudo apt install expect

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup LXD
      uses: ./.github/setup-lxd

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'

    - name: setup env
      shell: bash
      run: |
        echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Install local Juju
      shell: bash
      run: |
        make go-install

    - name: Smoke Test
      shell: bash
      run: |
        cd tests
        ./main.sh -v -s 'test_build' smoke
