name: "Snapcraft"
on:
  push:
    branches: ["[0-9].[0-9]+", "[0-9].[0-9]+.[0-9]+", main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "**.go"
      - "go.mod"
      - "snap/**"
      - ".github/workflows/snap.yml"
  workflow_dispatch:

jobs:
  snap:
    name: linux-arm64
    runs-on: [self-hosted, linux, arm64, aws, large]
    if: github.event.pull_request.draft == false
    steps:
      - name: Install Dependencies
        shell: bash
        run: |
          set -euxo pipefail
          sudo snap install snapcraft --classic
          echo "/snap/bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup LXD
        uses: canonical/setup-lxd@2fa6235ef2dfd3288e0de09edac03f2ebf922968

      - name: Set up Go
        if: env.RUN_TEST == 'RUN'
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: false

      - name: Build snap
        shell: bash
        run: |
          set -euxo pipefail
          snapcraft --use-lxd

      - name: Install snap
        shell: bash
        run: |
          set -euxo pipefail
          sudo snap install *.snap --dangerous --classic

      - name: Test bootstrap
        shell: bash
        run: |
          set -euxo pipefail
          juju bootstrap localhost
