name: "Snapcraft"
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - '**.go'
      - 'go.mod'
      - 'snap/**'
      - '.github/workflows/snap.yml'
  workflow_dispatch:
permissions:
  contents: read

jobs:

  snap:
    name: linux-amd64
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:

    - name: Install Dependencies
      shell: bash
      run: |
        set -euxo pipefail
        sudo snap install snapcraft --classic
        
        sudo apt-get remove lxd lxd-client
        if snap info lxd | grep "installed"; then
          sudo snap refresh lxd --channel=latest/stable
        else
          sudo snap install lxd --channel=latest/stable
        fi        
        
        sudo lxd waitready
        sudo lxd init --auto
        sudo chmod a+wr /var/snap/lxd/common/lxd/unix.socket
        echo "/snap/bin" >> $GITHUB_PATH

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      if: env.RUN_TEST == 'RUN'
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'

    - name: Build snap
      shell: bash
      run: |
        set -euxo pipefail
        snapcraft --use-lxd

    - name: Install snap
      shell: bash
      run: |
        set -euxo pipefail
        sudo snap install *.snap --dangerous
        # Since we're installing dangerously, we need to
        # manually grant permissions to juju
        sudo snap connect juju:lxd lxd
        sudo snap connect juju:config-lxd
        sudo snap connect juju:dot-local-share-juju
        sudo snap connect juju:ssh-keys
        snap connections juju

    - name: Test bootstrap
      shell: bash
      run: |
        set -euxo pipefail
        lxc network set lxdbr0 ipv6.address none
        mkdir ~/.ssh
        juju bootstrap localhost --debug
